# Generated by Django 4.2 on 2023-08-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image1_remove_post_image2'),
        ('user', '0002_alter_usercomments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
